FROM  python:3.11
LABEL neme="TestPanelApp"

# ## Env variables
ENV APP_HOME /app
ENV PYTHONPATH $APP_HOME
# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1
# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1
# ENV PIPENV_VENV_IN_PROJECT=1

# Set working directory
WORKDIR $APP_HOME

# Install & use pipenv
COPY Pipfile Pipfile.lock ./
RUN python -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --dev

# Copy files
COPY frontend ./frontend
COPY lib ./lib

EXPOSE 5006

ENTRYPOINT ["pipenv","run","frontend_dev"]
